package environmentalDataLogging.entities;

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.UUID;

/**
 * The SampleId entity class is the link to the sample_id table in the EnviroDB database.
 * A SampleId three values that uniquely create a project ID when combined together
 * Format XXX1111Y222 - XXX
 */
@Entity
@Table(name = "sample_id")
public class SampleId {
    /**
     *The unique auto generated id for a ProjectId
     */
    @Id
    @GenericGenerator(name = "uuid-gen", strategy = "uuid2")
    @GeneratedValue(generator = "uuid-gen")
    private UUID id;

    /**
     *The first value containing the ID in which the accounting department assigns
     */
    private String companyName;

    /**
     *The second value containing the ID that the client assigns
     */
    private String yearMonth;

    /**
     *The third value containing the ID that is generated by the project manager
     */
    private String sampleNumber;


    public String getCompanyName()
    {
        return companyName;
    }

    public void setCompanyName(String companyName)
    {
        this.companyName = companyName;
    }

    public String getYearMonth()
    {
        return yearMonth;
    }

    public void setYearMonth(String yearMonth)
    {
        this.yearMonth = yearMonth;
    }

    public String getSampleNumber()
    {
        return sampleNumber;
    }

    public void setSampleNumber(String sampleNumber)
    {
        this.sampleNumber = sampleNumber;
    }
}
