package environmentalDataLogging.models;

import java.util.UUID;

/**
 * The ProjectIdModel class is a copy to the ProjectId entity.
 * A ProjectId three values that uniquely create a project ID when combined together
 */
public class ProjectIdModel
{
    /**
     *The unique auto generated id for a projectId
     */
    private UUID id;

    /**
     *The first value containing the ID in which the accounting department assigns
     */
    private String value1;

    /**
     *The second value containing the ID that the client assigns
     */
    private String value2;

    /**
     *The third value containing the ID that is generated by the project manager
     */
    private String value3;


    /**
     * Gets id.
     *
     * @return the id
     */
    public UUID getId()
    {
        return id;
    }

    /**
     * Sets id.
     *
     * @param id the id
     */
    public void setId(UUID id)
    {
        this.id = id;
    }

    /**
     * Gets value 1.
     *
     * @return the value 1
     */
    public String getValue1()
    {
        return value1;
    }

    /**
     * Sets value 1.
     *
     * @param value1 the value 1
     */
    public void setValue1(String value1)
    {
        this.value1 = value1;
    }

    /**
     * Gets value 2.
     *
     * @return the value 2
     */
    public String getValue2()
    {
        return value2;
    }

    /**
     * Sets value 2.
     *
     * @param value2 the value 2
     */
    public void setValue2(String value2)
    {
        this.value2 = value2;
    }

    /**
     * Gets value 3.
     *
     * @return the value 3
     */
    public String getValue3()
    {
        return value3;
    }

    /**
     * Sets value 3.
     *
     * @param value3 the value 3
     */
    public void setValue3(String value3)
    {
        this.value3 = value3;
    }
}
